"""renamed status

Revision ID: 6cfbc575da99
Revises: 79ee1fa0fc6e
Create Date: 2025-01-02 10:16:44.191271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cfbc575da99'
down_revision: Union[str, None] = '79ee1fa0fc6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('tasks', 'is_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_completed', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
